- name: Install haproxy
  ansible.builtin.apt:
    name:
      - haproxy
    state: latest

- name: Configure haproxy
  ansible.builtin.copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
