- name: Install haproxy
  ansible.builtin.apt:
    name:
      - haproxy
    state: latest

- name: Configure haproxy
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Create haproxy configs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode|default('0640') }}"
  loop:
  - { src: haproxy.cfg.j2, dest: /etc/haproxy/haproxy.cfg }
  - { src: haproxy-ssl.sh.j2, dest: /etc/systemd/scripts/haproxy-ssl.sh, mode: "0755" }
  notify: restart haproxy

- name: Configure haproxy cert renewal service
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode|default('0644') }}"
  loop:
  - { src: haproxy-ssl.service, dest: /etc/systemd/system/ }
  - { src: haproxy-ssl.timer, dest: /etc/systemd/system/ }

- name: Enable haproxy cert renewal timer
  ansible.builtin.systemd:
    name: haproxy-ssl.timer
    state: started
    enabled: true
    daemon_reload: true
