- name: Check if disk is max size
  ansible.builtin.shell: |
    growpart /dev/sda 5 --dry-run  
  register: r_vgs_free
  ignore_errors: true

- name: Extend disk to max available
  ansible.builtin.shell: |
    growpart /dev/sda 5
    pvresize /dev/sda5
    lvextend -l +100%FREE /dev/debian-vg/root
    resize2fs /dev/debian-vg/root
  when: '"CHANGED" in r_vgs_free.stdout'
