- name: Get latest jamlab-packer
  ansible.builtin.git:
    repo: https://github.com/JamFox/jamlab-packer.git
    dest: "{{ provision_dir }}/jamlab-packer"
    version: main

- name: Get latest jamlab-terraform
  ansible.builtin.git:
    repo: https://github.com/JamFox/jamlab-terraform.git
    dest: "{{ provision_dir }}/jamlab-terraform"
    version: main

- name:
  ansible.builtin.template:
    src: pve.hcl.j2
    dest: "{{ pve_connection_hcl_location }}"
    mode: "0700"
  no_log: true

- name: Check if vm template exists
  ansible.builtin.shell: jq '.ids | has("100")' /etc/pve/.vmlist
  register: r_vm_template_exists

- name: Build base vm template
  ansible.builtin.shell: |
    cd "{{ provision_dir }}"/jamlab-packer/"{{ vm_template_name }}"
    PACKER_LOG=1 /usr/bin/packer build -var-file "{{ pve_connection_hcl_location }}" "{{ vm_template_name }}".pkr.hcl > /var/log/vm-template-build.log 2>&1
  when: r_vm_template_exists.stdout != "true"

- name: Provision vms
  ansible.builtin.shell: |
    cd "{{ provision_dir }}"/jamlab-terraform
    terraform apply -var-file "{{ pve_connection_hcl_location }}" -auto-approve > /var/log/vm-provision.log 2>&1
  when: r_vm_template_exists.stdout != "true"
