- name: Create nomad job dirs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group|default(item.owner) }}"
    mode: "{{ item.mode|default('0750') }}"
  loop:
  - { path: /opt/nomad-jobs/, owner: nomad, group: nomad-access }

- name: Template nomad jobs
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/nomad-jobs/{{ item | basename | regex_replace('\.j2$', '') }}
    mode: "{{ item.mode|default('0664') }}"
    owner: nomad
    group: nomad-access
  with_fileglob:
    - ../templates/*.j2

- name: Update all nomad jobs from /opt/nomad-jobs/
  ansible.builtin.shell: find /opt/nomad-jobs/ -maxdepth 1 -name "*.nomad" -type f -exec /usr/bin/nomad job run -detach {} \;

# FABIO

- name: Change fabio noroute page
  uri:
    url: "http://{{ consul.local_addr }}/{{ consul.api_endpoint }}/kv/fabio/noroute.html"
    method: PUT
    body: "<html><body><h1>Fabio: No route found for this request!</h1></body></html>"
    status_code: 200
