- name: Check if Proxmox setup was done
  ansible.builtin.stat:
    path: /opt/jamlab-setup/PROXMOX_SSL_SETUP_DONE
  register: r_proxmox_ssl

- name: Setup Proxmox SSL
  block:

  - name: Install Proxmox domain certificates
    ansible.builtin.shell: |
      /root/.acme.sh/acme.sh --installcert -d {{ ansible_hostname }}.jamfox.dev \
      --certpath /etc/pve/local/pveproxy-ssl.pem \
      --keypath /etc/pve/local/pveproxy-ssl.key  \
      --capath  /etc/pve/local/pveproxy-ssl.pem  \
      --reloadcmd  "systemctl restart pveproxy"

  - name: Create a new file with permissions
    file:
      path: /opt/jamlab-setup/PROXMOX_SSL_SETUP_DONE
      state: touch
      mode: "0700"

  when: not r_proxmox_ssl.stat.exists
