- name: Check /opt/PROXMOX_SSL_SETUP_DONE
  ansible.builtin.stat:
    path: /opt/PROXMOX_SSL_SETUP_DONE
  register: r_proxmox_ssl

- name: Install Proxmox domain certificates
  ansible.builtin.shell: |
    /root/.acme.sh/acme.sh --installcert -d {{ ansible_hostname }}.jamfox.dev \
    --certpath /etc/pve/local/pveproxy-ssl.pem \
    --keypath /etc/pve/local/pveproxy-ssl.key  \
    --capath  /etc/pve/local/pveproxy-ssl.pem  \
    --reloadcmd  "systemctl restart pveproxy"
    touch /opt/PROXMOX_SSL_SETUP_DONE
  when: not r_proxmox_ssl.stat.exists
