- name: Add extra keys and sources
  block:

  - name: Add extra keys
    ansible.builtin.get_url:
      url: "{{ item.key_url }}"
      dest: "{{ item.key_dest }}"
    loop: "{{ extra_sources }}"
    
  - name: Add extra sources
    ansible.builtin.apt_repository:
      repo: "{{ item.dist }} [signed-by={{ item.key_dest }}] {{ item.repo_url }} {{ ansible_distribution_release }} {{ item.repo_name }}"
      state: present
    loop: "{{ extra_sources }}"
  
  when: extra_sources is defined

- name: Install extra packages
  ansible.builtin.apt:
    name: "{{ extra_pkgs }}"
    state: latest
  when: extra_pkgs is defined
