- name: restart consul
  ansible.builtin.systemd:
    name: consul.service
    state: restarted
    daemon_reload: true

- name: restart nomad
  ansible.builtin.systemd:
    name: nomad.service
    state: restarted
    daemon_reload: true