- name: PLAYBOOK FOR GROUP 'VM_SVC'
  hosts: vm_svc

  roles:

  - { role: pre, tags: [ pre ], when: not (disabled_roles.pre | default(false)) }
  - { role: vm, tags: [ vm ], when: not (disabled_roles.vm | default(false)) }
  - { role: hashistack, tags: [ hashistack ], when: not (disabled_roles.hashistack | default(false)) }
