- name: Disable systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped

- name: Install dnsmasq
  ansible.builtin.apt:
    name:
      - dnsmasq
    state: latest

- name: Configure dnsmasq
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: /etc/dnsmasq.d/
  loop:
  - { src: jamlab-dns.conf }
  - { src: jamlab-records.conf }
  - { src: jamlab-consul.conf }
  notify: restart dnsmasq
