# Managed by jamlab-ansible
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[consul]
endpoint = "127.0.0.1:8500"
watch = true
prefix = "traefik"
#    [consul.tls]
#    ca = "/etc/ssl/ca.crt"
#    cert = "/etc/ssl/consul.crt"
#    key = "/etc/ssl/consul.key"
#    insecureSkipVerify = true

[consulCatalog]
endpoint = "127.0.0.1:8500"
exposedByDefault = true
stale = false
domain = "jamfox.dev"
strictChecks = true
prefix = "traefik"
frontEndRule = "Host:{{.ServiceName}}.{{.Domain}}"
#    [consulCatalog.tls]
#    ca = "/etc/ssl/ca.crt"
#    cert = "/etc/ssl/consul.crt"
#    key = "/etc/ssl/consul.key"
#    insecureSkipVerify = true

[acme]
email = "acme@jamfox.dev"
storage = "traefik/acme/account"
entryPoint = "https"
# Enable certificate generation on frontends host rules.
#onHostRule = true
# Uncomment the line to use Let's Encrypt's staging server, leave commented to go to prod
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
[acme.dnsChallenge]
  # Needs NAMECHEAP_API_USER, NAMECHEAP_API_KEY
  provider = "namecheap"
  delayBeforeCheck = 0
[[acme.domains]]
  main = "*.jamfox.dev"
  sans = ["jamfox.dev"]

[api]
  dashboard = true
  insecure = true
  debug = true

[metrics]
  [metrics.prometheus]

[log]
  level = "INFO"
