# Managed by jamlab-ansible
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":8082"

api:
  dashboard: true
  debug: true
  insecure: true

ping: {}

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

# Requires NAMECHEAP_API_USER, NAMECHEAP_API_KEY
#certificatesResolvers:
#  myresolver:
#    acme:
#      email: "acme@jamfox.dev"
#      storage: "/etc/traefik/acme.json"
#      # Comment out to use prod instead of staging
#      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
#      dnsChallenge:
#        provider: namecheap
#        delayBeforeCheck: 0

providers:
  nomad:
    refreshInterval: 30s
    prefix: traefik
    stale: false
    endpoint:
      address: https://127.0.0.1:4646
      tls:
        ca: /etc/nomad.d/nomad-ca.pem
        cert: /etc/nomad.d/nomad-server.pem
        key: /etc/nomad.d/nomad-server-key.pem
  consulCatalog:
    refreshInterval: 30s
    prefix: traefik
    requireConsistent: true
    endpoint:
      address: 127.0.0.1:8501
      scheme: https
      tls:
        ca: /etc/consul.d/consul-agent-ca.pem
        cert: /etc/consul.d/dc1-cli-consul-0.pem
        key: /etc/consul.d/dc1-cli-consul-0-key.pem
    defaultRule:  "Host(`{{ .Name }}.jamfox.dev`)"
    connectAware: true
    connectByDefault: true
    watch: true
      