- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install snapd
  ansible.builtin.apt:
    name:
      - snapd
    state: latest

- name: Install and refresh snap core
  ansible.builtin.shell: snap install core; snap refresh core

- name: Install base packages
  ansible.builtin.apt:
    name:
      - jq
      - curl
      - wget
      - vim 
      - git 
      - ansible 
      - keychain 
      - tmux 
      - python3
      - logrotate
      - net-tools
      - build-essential 
      - procps 
      - file
      - gpg
      - sudo
      - unattended-upgrades
    state: latest

- name: Set unattended security patches
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    block: |
      Unattended-Upgrade::Mail "unattended-upgrade@jamfox.dev";
      Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      Unattended-Upgrade::Remove-New-Unused-Dependencies "true";
      Unattended-Upgrade::Automatic-Reboot "false";
      Unattended-Upgrade::Automatic-Reboot-Time "04:00";
    marker: "# {mark} BLOCK Managed by jamlab-ansible"

- name: restart unattended-upgrades service
  ansible.builtin.systemd:
    name: unattended-upgrades.service
    state: restarted
