- name: Add Hashicorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc

- name: Add Hashicorp source
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Update apt cache and upgrade packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install snapd
  ansible.builtin.apt:
    name:
      - snapd
    state: latest

- name: Install and refresh snap core
  ansible.builtin.shell: snap install core; snap refresh core

- name: Install base packages
  ansible.builtin.apt:
    name:
      - jq
      - curl
      - wget
      - vim 
      - git 
      - ansible 
      - keychain 
      - tmux 
      - python3
      - logrotate
      - net-tools
      - build-essential 
      - procps 
      - file
      - gpg
      - sudo
    state: latest