# DDNS

- name: Install ddclient
  ansible.builtin.apt:
    name:
      - ddclient
    state: latest

- name: Configure ddclient
  ansible.builtin.template:
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
  notify: restart ddclient
  no_log: true

# CERTBOT

- name: Remove system default certbot
  ansible.builtin.apt:
    name:
      - certbot
    state: absent

- name: Check /snap/bin/certbot
  ansible.builtin.stat:
    path: /snap/bin/certbot
  register: r_certbot

- name: Install cerbot from snap
  ansible.builtin.shell: snap install --classic certbot; snap set certbot trust-plugin-with-root=ok; snap install certbot-dns-cloudflare
  when: not r_certbot.stat.exists

- name: Link certbot to /usr/bin
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Set cloudflare certbot credentials
  ansible.builtin.copy:
    dest: /root/.certbot.ini
    mode: "0600"
    content: |
      dns_cloudflare_api_token = {{ dns_api.token }}
  no_log: true

- name: Check if cert exists
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ domain.default }}/"
  register: r_letsencrypt_live

- name: Get letsencrypt cert
  ansible.builtin.shell: certbot certonly --non-interactive --agree-tos -m acme@{{ domain.default }} --dns-cloudflare --dns-cloudflare-credentials /root/.certbot.ini -d {{ domain.default }},*.{{ domain.default }} --preferred-challenges dns-01
  when: not r_letsencrypt_live.stat.exists
