# 'pre' main is used to call all prerequisite roles on all machines.
- name: Include init role
  ansible.builtin.include_role:
    name: init
    apply:
      tags: [ init ]
  when: not disabled_roles.init | default(false)
  tags: always

- name: Include base_pkg role
  ansible.builtin.include_role:
    name: base_pkg
    apply:
      tags: [ base_pkg ]
  when: not (disabled_roles.base_pkg | default(false))
  tags: always

- name: Include auth role
  ansible.builtin.include_role:
    name: auth
    apply:
      tags: [ auth ]
  when: not (disabled_roles.auth | default(false))
  tags: always

- name: Include motd role
  ansible.builtin.include_role:
    name: motd
    apply:
      tags: [ motd ]
  when: not (disabled_roles.motd | default(false))
  tags: always