- name: PLAYBOOK FOR GROUP 'VM_BASE'
  hosts: vm_base

  roles:

  - { role: pre, tags: [ pre ], when: not (disabled_roles.pre | default(false)) }
  - { role: hashistack, tags: [ hashistack ], when: not (disabled_roles.hashistack | default(false)) }
  - { role: traefik, tags: [ traefik ], when: not (disabled_roles.traefik | default(false)) }
